### ISSUE TITLE
Make maximum archive size for loading modifiable through command line option

### ISSUE THREAD

**Issue by skyman** [zucchini/zucchini#43]
Right now, the limit is hard-coded (as of #42, at 64 MiB).

We don't want people messing with the internals of zucchini - we need this limit to be modifiable on demand, so we should support it as a command line option for the load command when flattening loaders are used.

**Comment by ausbin** [comment]
thanks for making this. i'm thinking we set an error flag for the submission (which i'm gonna do for #41), then when you run `show-grades`  you'll see a message which tells you something like `archive was too big (11 MiB > 10 MiB). to try again, run zucc load canvas -s 'Leahy, Bill' --max-archive-size 0`
